---
- name: Release an IP in a CIDR block
  hosts: localhost
  become: false
  gather_facts: false
  tasks:
    - name: Get IP info
      kenmoini.phpipam.address_info:
        ip: "{{ ip_address }}"
        phpipam_url: "{{ phpipam_url }}"
        phpipam_app_id: "{{ phpipam_app_id }}"
        phpipam_app_code: "{{ phpipam_app_code }}"
        phpipam_skip_tls_verify: "{{ phpipam_skip_tls_verify }}"
      register: address_info
      changed_when: (address_info.ip | default([])) | length > 0
      when: ip_address is ansible.utils.ip_address

    - name: Release the IP address
      kenmoini.phpipam.release_address:
        subnet_id: "{{ address_info['address_info'][0]['subnetId'] }}"
        ip_id: "{{ address_info['address_info'][0]['id'] }}"
        phpipam_url: "{{ phpipam_url }}"
        phpipam_app_id: "{{ phpipam_app_id }}"
        phpipam_app_code: "{{ phpipam_app_code }}"
        phpipam_skip_tls_verify: "{{ phpipam_skip_tls_verify }}"
      register: release_result
      changed_when: release_result.ip_address.message | default('') == "Address deleted"
      when:
        - ip_address is ansible.utils.ip_address
        - (address_info.ip | default([])) | length > 0